# Configuration data for cities, temperature, humidity, and wind speed

cities:
  - New York
  - London
  - Tokyo

temperature_range:
  min: 20
  max: 35

humidity_range:
  min: 40
  max: 80

wind_speed_range:
  min: 5
  max: 20
